//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Collections.Generic;
    
    public partial class top_tweets_numbered
    {
        public long RN { get; set; }
        public string user_name { get; set; }
        public Nullable<int> tweet_followers_count { get; set; }
    }
}
