//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TweetData> TweetDatas { get; set; }
        public DbSet<top_tweets_numbered> top_tweets_numbered { get; set; }
        public DbSet<Tweet> Tweets { get; set; }
        public DbSet<most_retweets_numbered> most_retweets_numbered { get; set; }
        public DbSet<TweetStream> TweetStreams { get; set; }
    
        public virtual ObjectResult<sp_most_retweets_numbered_Result> sp_most_retweets_numbered()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_most_retweets_numbered_Result>("sp_most_retweets_numbered");
        }
    }
}
